# ==========================================
# Stage 1: 源码下载阶段 (Downloader)
# ==========================================
FROM alpine/git:latest AS downloader

WORKDIR /src

RUN git clone -b MitFrame --depth 1 https://gitee.com/Discuz/DiscuzX.git .

COPY entrypoint-alpine.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

# ==========================================
# Stage 2: 最终运行阶段 (Final Runtime)
# ==========================================
FROM alpine:latest

ARG TARGETARCH

# 1. 安装运行时必需的系统依赖 # 2. 安装 PHP 扩展 # 3. 提权设置
RUN apk add ca-certificates curl su-exec libcap-setcap \
    && if [ "$TARGETARCH" = "arm64" ]; then \
        FILENAME="frankenphp-linux-aarch64"; \
    else \
        FILENAME="frankenphp-linux-x86_64"; \
    fi && \
    curl -L "https://github.com/dunglas/frankenphp/releases/latest/download/${FILENAME}" -o /usr/local/bin/frankenphp \
    && chmod +x /usr/local/bin/frankenphp \
    && setcap cap_net_bind_service=+ep /usr/local/bin/frankenphp

ENV XDG_CONFIG_HOME=/config
ENV XDG_DATA_HOME=/data

# 4. 从下载阶段拷贝源码
WORKDIR /usr/src/discuz
COPY --from=downloader /src/upload /usr/src/discuz

# 5. 准备脚本和配置
COPY --from=downloader /usr/local/bin/entrypoint.sh /usr/local/bin/entrypoint.sh

COPY Caddyfile /etc/caddy/Caddyfile

# 6. 入口设置
WORKDIR /app/public
ENTRYPOINT ["entrypoint.sh"]
CMD ["frankenphp", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]
